### ISSUE TITLE
Feature Request: In Metric Scaling Mode Add SI Prefixes for n < 1

### ISSUE THREAD

**Issue by 9-FS** [kdr-aus/numfmt#10]
In metric scaling mode `m`, please add the corresponding [metric prefixes for numbers smaller than 1](https://en.wikipedia.org/wiki/Metric_prefix), like milli, mikro, nano, pico, femto, atto...
- 10^(-3) => "1m"
- 10^(-6) => "1µ"
- 10^(-9) => "1n"
- ...

It would make sense to default to scientific notation only when metric prefixes are exhausted. Currently, the smallest metric prefix is "quecto" meaning 10^(-30). Only a number < 10^(-30) should be written in scientific notation.

Same behaviour on the other side: The biggest metric prefix is "quetta" at 10^30. I would expect a number going up to "999.99999Q" and as soon as it reaches 10^(33), where no metric prefix is defined, scientific notation should kick in. 

I personally am also of the opinion no fallback to scientific notation should kick in "no scaling mode" `n`, but that's another topic.

**Comment by 9-FS** [comment]
For everyone in the future coming here looking for that feature: Since this project seems abandoned, I wrote my own crate implementing the desired features called [`scaler`](https://crates.io/crates/scaler).

**Comment by kurtlawrence** [comment]
FWIW this project is not abandoned. You are welcome to raise PRs with functionality needed.
