### ISSUE TITLE
Support for other types of floats/ints

### ISSUE THREAD

**Issue by astrale-sharp** [kdr-aus/numfmt#2]
Hi, would you accept contribution in order to add or modify some feature so they could be used for other types of floats int : bigints bigfloats and custom ones?
If so I would be interested in implementing this (in order to use it in typst)

**Comment by kurtlawrence** [comment]
Hi @astrale-sharp, yes I would be interested.

I think if we implement this we would have to make it generic over the input. I'd be interested in seeing your implementation.

Other things to consider are the performance, and probably hiding dependencies behind feature flags.
